INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Café da manhã');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Almoço');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Jantar');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Um dia livre na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Dois dias livres na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Três dias livres na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Quatro dias livres na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Cinco dias livres na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Seis dias livres na semana');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Quarto compartilhado');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Quarto individual');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Uso livre da cozinha');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Lavanderia');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Descontos em festas');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Descontos em drinks');
INSERT INTO `viajalheira`.`beneficio` (`descricao`) VALUES ('Descontos em passeios');
